# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.activity_download_service:
        class: AppBundle\Services\ActivitiesDownloadService


#Factories
    app.activity_factory:
        class: AppBundle\Factory\ActivityFactory
        arguments: ["@doctrine.orm.entity_manager"]